version: '3.8'
name: ostock
services:
  maven:
    build:
      context: ../maven
  config-service:
    build:
      context: ../config-service
      target: run
    ports:
      - 8071:8071
    environment:
      - ENCRYPT_KEY_FILE=/run/secrets/encrypt_key
      - GIT_USERNAME_FILE=/run/secrets/git/username
      - GIT_PASSWORD_FILE=/run/secrets/git/password
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/biya-bi/ostock-configs
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS=*
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULTLABEL=main
    volumes:
      - ./secrets/dev/config-service/encrypt_key:/run/secrets/encrypt_key
      - ./secrets/dev/git/:/run/secrets/git/
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
  eureka-service:
    build:
      context: ../eureka-service
      target: run
    ports:
      - 8070:8070
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8071
    volumes:
      - ./:/app
    depends_on:
      config-service:
        condition: service_healthy
  licensing-service:
    build:
      context: ../licensing-service
      target: run
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8071
      - EUREKA_URI=http://eureka-service:8070/eureka
    volumes:
      - ./:/app
    depends_on:
      config-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
  organization-service:
    build:
      context: ../organization-service
      target: run
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8071
      - EUREKA_URI=http://eureka-service:8070/eureka
    volumes:
      - ./:/app
    depends_on:
      config-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
  postgres:
    build:
      context: ../postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres/user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres/password
      - POSTGRES_DB_FILE=/run/secrets/postgres/db
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets/dev/postgres/:/run/secrets/postgres/
      - ../postgres/scripts/dev/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ../postgres/scripts/dev/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$(cat /run/secrets/postgres/user)\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 9080:8080
  gateway-service:
    build:
      context: ../gateway-service
      target: run
    ports:
      - 8072:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8071
      - EUREKA_URI=http://eureka-service:8070/eureka
    volumes:
      - ./:/app
    depends_on:
      config-service:
        condition: service_healthy
volumes:
  postgres_data: