version: '3.8'
name: ostock
services:
  config-server:
    build:
      context: ../config-server
      target: run
    ports:
      - 8071:8071
  licensing-service:
    build:
      context: ../licensing-service
      target: run
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres/ostock
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
    volumes:
      - ./:/app
    depends_on:
      - config-server
      - postgres
  postgres:
    build:
      context: ../postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets/databases/postgres/:/run/secrets/postgres/
      - ../postgres/scripts:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 9080:8080
volumes:
  postgres_data: