version: '3.8'
name: ostock
services:
  config-server:
    build:
      context: ../config-server
      target: run
    ports:
      - 8071:8071
    environment:
      - ENCRYPT_KEY_FILE=/run/secrets/encrypt_key
    volumes:
      - ./secrets/config-server/encrypt_key:/run/secrets/encrypt_key
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
  licensing-service:
    build:
      context: ../licensing-service
      target: run
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres/ostock
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
    volumes:
      - ./:/app
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
  postgres:
    build:
      context: ../postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets/databases/postgres/:/run/secrets/postgres/
      - ../postgres/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$(cat /run/secrets/postgres/user)\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 9080:8080
volumes:
  postgres_data: