version: '3.8'
name: ostock
services:
  17-jdk-jammy-maven:
    build:
      context: ../17-jdk-jammy-maven
  config-service:
    build:
      context: ../config-service
      target: run
    restart: always
    environment:
      - ENCRYPT_KEY_FILE=/run/secrets/encrypt_key
      - GIT_USERNAME_FILE=/run/secrets/git/username
      - GIT_PASSWORD_FILE=/run/secrets/git/password
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/biya-bi/ostock-configs
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS=*
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULTLABEL=main
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULT=http://eureka-service:8080/eureka
    volumes:
      - ./secrets/dev/config-service/encrypt_key:/run/secrets/encrypt_key
      - ./secrets/dev/git/:/run/secrets/git/
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
  eureka-service:
    build:
      context: ../eureka-service
      target: run
    ports:
      - 8070:8080
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8080
    volumes:
      - ./:/app
    depends_on:
      config-service:
        condition: service_healthy
  licensing-service:
    build:
      context: ../licensing-service
      target: run
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8080
      - EUREKA_URI=http://eureka-service:8080/eureka
      - JWT_ISSUER_URI_FILE=/run/secrets/keycloak/jwt_issuer_uri
    volumes:
      - ./:/app
      - ./secrets/dev/keycloak/:/run/secrets/keycloak/
    depends_on:
      config-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
  organization-service:
    build:
      context: ../organization-service
      target: run
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8080
      - EUREKA_URI=http://eureka-service:8080/eureka
      - JWT_ISSUER_URI_FILE=/run/secrets/keycloak/jwt_issuer_uri
    volumes:
      - ./:/app
      - ./secrets/dev/keycloak/:/run/secrets/keycloak/
    depends_on:
      config-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
  postgres:
    build:
      context: ../postgres
    restart: always
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres/user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres/password
      - POSTGRES_DB_FILE=/run/secrets/postgres/db
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets/dev/postgres/:/run/secrets/postgres/
      - ../postgres/scripts/dev/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ../postgres/scripts/dev/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$(cat /run/secrets/postgres/user)\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 9080:8080
  gateway-service:
    build:
      context: ../gateway-service
      target: run
    restart: always
    ports:
      - 8072:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8080
      - EUREKA_URI=http://eureka-service:8080/eureka
      - JWT_ISSUER_URI_FILE=/run/secrets/keycloak/jwt_issuer_uri
    volumes:
      - ./:/app
      - ./secrets/dev/keycloak/:/run/secrets/keycloak/
    depends_on:
      config-service:
        condition: service_healthy
  angular-service:
    build:
      context: ../angular-service
    ports:
      - 4200:4200
  notification-service:
    build:
      context: ../notification-service
      target: run
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8080
      - EUREKA_URI=http://eureka-service:8080/eureka
      - JWT_ISSUER_URI_FILE=/run/secrets/keycloak/jwt_issuer_uri
      - VAPID_PRIVATE_KEY_FILE=/run/secrets/vapid/private_key
      - VAPID_PUBLIC_KEY_FILE=/run/secrets/vapid/public_key
      - VAPID_SUBJECT_FILE=/run/secrets/vapid/subject
    volumes:
      - ./:/app
      - ./secrets/dev/keycloak/:/run/secrets/keycloak/
      - ./secrets/dev/notifications/vapid/:/run/secrets/vapid/
    depends_on:
      config-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
volumes:
  postgres_data: